### ISSUE TITLE
[Feature request] Option for disabling icons preview page generation

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/svg-sprite-module#113] opened 2019-11-22 15:40 UTC
This request is an easy fix for this [issue](https://github.com/nuxt-community/svg-sprite-module/issues/111)
There are also cases when user may want to have a custom icons preview page he has complete control over. Right now there is no way to customize the generated page.
Disabling of the page generation will also speed up compilation for a bit

**Comment by danirod** [comment] 2019-11-27 10:02
We are currently experience regressions when upgrading to @nuxtjs/svg-sprite@0.4.5 in one of our projects too because of the same bug described in #111. We use a custom output path for the generated SVG sprite, and we are unable to start the server in development mode due to build errors related to this module.

I've opened #115 to introduce a flag that makes possible to disable the generation of this page, which fixes the bug. In our case, a test page listing all the icons is something already managed by our Storybook project.

**Comment by farnabaz** [comment] 2019-11-27 19:03
I don't think disabling list page is a solution to this issue.
I've created a patch for the issue

Close #116

**Comment by danirod** [comment] 2019-11-28 07:28
Indeed, this was not a fix, it was more like a curtain to hide the bug. 😛
However, it was also easier to do than patching the template.

**Comment by AndrewBogdanovTSS** [comment] 2019-12-10 10:04
@farnabaz so should we do with this issue? Just close it without an implementation of such option ?

**Comment by farnabaz** [comment] 2019-12-13 20:58
@AndrewBogdanovTSS I'm not interested in implementing this option. Icons page registers in development mode and it never conflicts with project routes, so I think this option is not necessary.

**Comment by AndrewBogdanovTSS** [comment] 2019-12-16 07:55
@farnabaz btw, is there a way to force it to be present not only in dev but also in production mode? We have a visual department who doesn't have access to the repo, so it would be convenient if they also could have an access to the page that lists all the icons

**Comment by farnabaz** [comment] 2019-12-19 15:53
@AndrewBogdanovTSS Currently this is not possible, because of the hard-coded condition.
I'll be working on it, so in next releases, icons page can be enabled or disabled in config independent of development mode

**Comment by AndrewBogdanovTSS** [comment] 2019-12-20 09:12
Could you also expose a data object that would have a reference to all available icon names so that people could easily build their own list out of it? I think it would be much more convenient than a static page users can't modify

**Comment by farnabaz** [comment] 2020-09-02 14:47
In the latest version:
- It is possible to disable icons page, by setting the `iconsPath` option to `false`
- The module generates `sprites.json` in output directory, This file can be used for generating custom icons list

I close this issue, feel free to reopen it or comment :)

**Closed by farnabaz** 2020-09-02 14:47 UTC

**Comment by AndrewBogdanovTSS** [comment] 2020-09-02 15:05
It's already working as it should, thanks @farnabaz 👍
